spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_36_shop
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    username: leonid.kleimann@ait-tr.de
    password: ilipsxlagchovjbm
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

key:
  access: u6IWyTFLVdjo0lv58z/jdQlBfoL970Ty8neqaM+D6/g=
  refresh: qzc/VaTdtsoo8cnZlogRiYIr7CqTtJOufkj60hELFQQ=

message:
  hello: Hello from Local Application!